name: client
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: ^0.8.4+5
  intl: ^0.17.0
  cached_network_image: ^3.2.3
  socket_io_client: ^2.0.0
  flutter_local_notifications: ^9.0.0+2
  provider: ^6.0.0
  timezone: ^0.8.0
  device_info_plus: ^10.1.0
  flutter_timezone: ^1.0.8
  path_provider: ^2.1.3
  smooth_page_indicator: ^1.0.0+2
  flutter_map: ^4.0.0 # or the latest version
  latlong2: ^0.8.1 # or the latest version
  http: ^0.13.3
  shared_preferences: ^2.0.6
  flutter_spinkit: ^5.1.0
  animated_bottom_navigation_bar: ^1.3.3
  auto_size_text: ^3.0.0
  circular_reveal_animation: ^2.0.1
  flutter_cube: ^0.1.1
  
 
  
  
  
  
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png
    - assets/facebook_logo.png
    - assets/logoa.png
    - assets/vehicle.obj
    - assets/disc.jpg
    - assets/caliper.jpg
    - assets/suspension.tga.jpg
    - assets/tread.tga.jpg
    - assets/jcw_glass.jpg
    - assets/jcw_lights.jpg
    - assets/jcw_wheel.jpg
    - assets/jcw_cabin.jpg
    - assets/jcw_main.jpg

    - assets/NGMD9KMV7CA4PLG6K7QP1N8VS.mtl
    - assets/vehicle_texture.png
    
