name: client
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: ^0.8.4+5
  intl: ^0.17.0
  cached_network_image: ^3.2.3
  socket_io_client: ^2.0.0
  flutter_local_notifications: ^9.0.0+2
  provider: ^6.0.0
  timezone: ^0.8.0
  device_info_plus: ^10.1.0
  flutter_timezone: ^1.0.8
  path_provider: ^2.1.3
  smooth_page_indicator: ^1.0.0+2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png
    - assets/facebook_logo.png
