import 'dart:io';
import 'package:client/models/car.dart';
import 'package:client/screens/sinistre/suivi_screen.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:client/ViewModel/sinistre_view_model.dart';
import 'package:client/models/sinistre.dart';
import 'package:image_picker/image_picker.dart';
import 'package:intl/intl.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:timezone/data/latest.dart' as tz;
import 'package:timezone/timezone.dart' as tz;
import 'package:client/screens/sinistre/mapScreen.dart';

class SinistreFormScreen extends StatefulWidget {
  const SinistreFormScreen({super.key});

  @override
  _SinistreFormScreenState createState() => _SinistreFormScreenState();
}

class _SinistreFormScreenState extends State<SinistreFormScreen> {
  final _formKey = GlobalKey<FormState>();
  String _claimType = '';
  String _description = '';
  DateTime? _incidentDate;
  bool _isLoading = false;
  List<XFile> _selectedImages = [];
  final ImagePicker _picker = ImagePicker();
  final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();
  String _selectedAddress = 'No address selected';

  @override
  void initState() {
    super.initState();
    tz.initializeTimeZones();
  }

  Future<void> showNotification(String title, String body) async {
    const AndroidNotificationDetails androidPlatformChannelSpecifics =
        AndroidNotificationDetails(
      'your_channel_id',
      'your_channel_name',
      channelDescription: 'your channel description',
      importance: Importance.max,
      priority: Priority.high,
      showWhen: false,
    );
    const NotificationDetails platformChannelSpecifics =
        NotificationDetails(android: androidPlatformChannelSpecifics);
    await flutterLocalNotificationsPlugin.show(
      0,
      title,
      body,
      platformChannelSpecifics,
    );
  }

  Future<void> _pickImage(ImageSource source) async {
    final pickedFile = await _picker.pickImage(source: source);
    if (pickedFile != null) {
      setState(() {
        _selectedImages.add(pickedFile);
      });
    }
  }

  void _submitForm() async {
    if (_formKey.currentState!.validate()) {
      setState(() {
        _isLoading = true;
      });

      _formKey.currentState!.save();

      final sinistreViewModel = Provider.of<SinistreViewModel>(context, listen: false);

      // Create a new sinistre
      Sinistre newSinistre = Sinistre(
        id: '1', // This should be generated by your backend
        userId: 'user1', // Replace with the actual user ID
        description: _description,
        status: 'Processing',
        location: _selectedAddress,
        photos: _selectedImages.map((file) => file.path).toList(),
        dateReported: _incidentDate ?? DateTime.now(),
        car: Car(
          id: '1', // This should be generated by your backend
          make: 'Toyota',
          model: 'Corolla',
          year: 2020,
          licensePlate: 'XYZ123',
          userId: 'user1', // Replace with actual user ID
          photos: _selectedImages.map((file) => file.path).toList(),
        ),
      );

      try {
        await sinistreViewModel.createSinistre(newSinistre);

        setState(() {
          _isLoading = false;
        });

        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Claim submitted successfully!')),
        );

        _formKey.currentState!.reset();
        setState(() {
          _claimType = '';
          _description = '';
          _incidentDate = null;
          _selectedImages = [];
          _selectedAddress = 'No address selected';
        });

        // Show notification on status change
        showNotification('Claim Status', 'Your claim status has changed.');

        // Schedule a notification
        final scheduledTime = DateTime.now().add(const Duration(minutes: 5)); // 5 minutes later
        scheduleNotification('Reminder', 'Check your claim status.', scheduledTime);

        // Navigate to SuiviScreen
        Navigator.pushReplacement(
          context,
          MaterialPageRoute(builder: (context) => SuiviScreen()),
        );
      } catch (e) {
        setState(() {
          _isLoading = false;
        });

        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Failed to submit claim. Please try again.')),
        );
      }
    }
  }

  Future<void> scheduleNotification(String title, String body, DateTime scheduledTime) async {
    await flutterLocalNotificationsPlugin.zonedSchedule(
      0,
      title,
      body,
      tz.TZDateTime.from(scheduledTime, tz.local),
      const NotificationDetails(
          android: AndroidNotificationDetails(
              'your_channel_id', 'your_channel_name',
              channelDescription: 'your channel description')),
      androidAllowWhileIdle: true,
      uiLocalNotificationDateInterpretation: UILocalNotificationDateInterpretation.absoluteTime,
    );
  }

  Future<void> _selectDate(BuildContext context) async {
    final DateTime? pickedDate = await showDatePicker(
      context: context,
      initialDate: _incidentDate ?? DateTime.now(),
      firstDate: DateTime(2000),
      lastDate: DateTime(2101),
    );
    if (pickedDate != null && pickedDate != _incidentDate) {
      setState(() {
        _incidentDate = pickedDate;
      });
    }
  }

  Future<void> _navigateToMapScreen(BuildContext context) async {
    final result = await Navigator.push(
      context,
      MaterialPageRoute(builder: (context) => MapScreen()),
    );

    if (result != null && result is String) {
      setState(() {
        _selectedAddress = result;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Report a New Claim'),
      ),
      body: Center(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(16.0),
          child: Form(
            key: _formKey,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Text(
                  'Claim Type',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                ),
                const SizedBox(height: 8),
                DropdownButtonFormField<String>(
                  decoration: const InputDecoration(
                    border: OutlineInputBorder(),
                    hintText: 'Select Claim Type',
                  ),
                  items: ['Accident', 'Theft', 'Damage', 'Other']
                      .map((label) => DropdownMenuItem(
                            value: label,
                            child: Text(label),
                          ))
                      .toList(),
                  onChanged: (value) {
                    setState(() {
                      _claimType = value!;
                    });
                  },
                  validator: (value) {
                    if (value == null || value.isEmpty) {
                      return 'Please select a claim type';
                    }
                    return null;
                  },
                  onSaved: (value) {
                    _claimType = value!;
                  },
                ),
                const SizedBox(height: 16),
                const Text(
                  'Description',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                ),
                const SizedBox(height: 8),
                TextFormField(
                  maxLines: 4,
                  decoration: const InputDecoration(
                    border: OutlineInputBorder(),
                    hintText: 'Enter a description of the claim',
                  ),
                  validator: (value) {
                    if (value!.isEmpty) {
                      return 'Please enter a description';
                    }
                    return null;
                  },
                  onSaved: (value) {
                    _description = value!;
                  },
                ),
                const SizedBox(height: 16),
                const Text(
                  'Date of Incident',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                ),
                const SizedBox(height: 8),
                InkWell(
                  onTap: () => _selectDate(context),
                  child: InputDecorator(
                    decoration: const InputDecoration(
                      border: OutlineInputBorder(),
                      hintText: 'Select Incident Date',
                    ),
                    child: Text(
                      _incidentDate == null
                          ? 'No date selected'
                          : DateFormat.yMMMd().format(_incidentDate!),
                    ),
                  ),
                ),
                const SizedBox(height: 16),
                const Text(
                  'Photos',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                ),
                const SizedBox(height: 8),
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                  children: [
                    ElevatedButton.icon(
                      icon: const Icon(Icons.camera),
                      label: const Text('Camera'),
                      onPressed: () => _pickImage(ImageSource.camera),
                    ),
                    ElevatedButton.icon(
                      icon: const Icon(Icons.photo),
                      label: const Text('Gallery'),
                      onPressed: () => _pickImage(ImageSource.gallery),
                    ),
                  ],
                ),
                const SizedBox(height: 16),
                if (_selectedImages.isNotEmpty)
                  SizedBox(
                    height: 100,
                    child: ListView.builder(
                      scrollDirection: Axis.horizontal,
                      itemCount: _selectedImages.length,
                      itemBuilder: (context, index) {
                        return Padding(
                          padding: const EdgeInsets.all(8.0),
                          child: Image.file(
                            File(_selectedImages[index].path),
                            height: 100,
                            width: 100,
                          ),
                        );
                      },
                    ),
                  ),
                const SizedBox(height: 16),
                const Text(
                  'Address',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                ),
                const SizedBox(height: 8),
                InkWell(
                  onTap: () => _navigateToMapScreen(context),
                  child: InputDecorator(
                    decoration: const InputDecoration(
                      border: OutlineInputBorder(),
                      hintText: 'Select Address',
                    ),
                    child: Text(_selectedAddress),
                  ),
                ),
                const SizedBox(height: 24),
                Center(
                  child: _isLoading
                      ? const CircularProgressIndicator()
                      : ElevatedButton(
                          onPressed: _submitForm,
                          style: ElevatedButton.styleFrom(
                            padding: const EdgeInsets.symmetric(horizontal: 40, vertical: 15),
                            textStyle: const TextStyle(fontSize: 18),
                          ),
                          child: const Text('Submit Claim'),
                        ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
